[package]
name = "chalk-protocol"
version = "1.0.0"

[[bin]]
default = true
bin_name = "default"

[bin.tools]
linker = "mold"

[bin.args]
compiler_args = "-O2 -fPIC"
linker_args = "-shared"
out_name = "${name}-${version}.so"

[bin.compiling]
before = ["mkdir -p ./target/lib ./target/obj"]
