[package]
name = "chalk-protocol"
version = "1.0.0"

[[bin]]
default = true
bin_name = "default"

[bin.tools]
linker = "mold"

[bin.args]
compiler_args = "-O2 -fPIC"
linker_args = "-shared"
out_path = "./target/lib"
out_name = "lib${name}-${version}.so"

[bin.compiling]
before = ["mkdir -p ./target/lib ./target/obj"]

[[bin]]
bin_name = "test"

[bin.tools]
linker = "mold"

[bin.meta]
header_dirs = "find ./src/include -type d"

[bin.args]
out_path = "./target/tests/bin"

[bin.compiling]
before = [
	"mkdir -p ./target/tests/bin ./target/tests/obj",
	"cp -r ./src/include ./test/",
]
run = [
	"${compiler} ${compiler_args} -c ./test/tcp_test.c -I ${header_dirs}",
	"${compiler} ${compiler_args} -c ./test/vector_test.c -I ${header_dirs}",
]
after = ["mv *.o ./target/tests/obj"]

[bin.linking]
run = [
	"${compiler} -B ${linker} ./target/tests/obj/tcp_test.o -o ${out_path}/tcp_test -L ./target/lib/ -l ${name}-${version}",
	"${compiler} -B ${linker} ./target/tests/obj/vector_test.o -o ${out_path}/vector_test -L ./target/lib/ -l ${name}-${version}",
]
after = [
	"LD_LIBRARY_PATH=./target/lib ./target/tests/bin/tcp_test",
	"LD_LIBRARY_PATH=./target/lib ./target/tests/bin/vector_test",
]
